---
title: "Report on Happiness up to 2022"
author:
- familyname: Yang 
  othernames: Zhixiang
  email: zyan0056@student.monash.edu
  correspondingauthor: true
  qualifications:  EBS Honours Student
- familyname: Wang
  othernames: Yiqi
  email: ywan0684@studnet.monash.edu
  qualifications: Master of BA Student
- familyname: You
  othernames: Xintong
  email: xyou0004@student.monash.edu
  correspondingauthor: true
  qualifications: Master of BA Student
phone: (03) 9905 2478
department: Department of\newline Econometrics &\newline Business Statistics
organization: Group 07 ETC5513
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  monash::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, message=FALSE, warning=FALSE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(sf)
library(here)
library(lubridate)
library(cowplot)
library(janitor)
library(maps)
library(plotly)
require(wbstats)
library(RColorBrewer)
library(repr)
library(gridExtra)
library(rworldmap) 
library(lemon)
```

# Exploratory data analysis

```{r read-data}
happiness_2020 <- read_csv(here("data", "2020.csv"))
happiness_2021 <- read_csv(here("data", "2021.csv"))
```

### What are the countries which ranks top 10 in happiness score since the COVID-19 outbreak?
```{r top_10,fig.cap="The top 10 countries in happiness score since"}
top10_2020 <- happiness_2020 %>%
  mutate(RANK = as.numeric(rownames(happiness_2020))) %>%
  select("RANK","Country name","Ladder score") %>%
  rename("Country" = "Country name",
         "Happiness score" = "Ladder score") %>%
  arrange(desc("Happiness score")) %>%
  head(n = 10)
top10_2021 <- happiness_2021 %>% 
  mutate(RANK = as.numeric(rownames(happiness_2021))) %>%
  select("RANK","Country name","Ladder score") %>% 
  rename("Country" = "Country name",
          "Happiness score" = "Ladder score") %>%
  arrange(desc("Happiness score"))  %>%
  head(n = 10)

g1 <- ggplot(top10_2020,
             aes(x=factor(Country,levels=Country),
                 y=RANK, color = Country))+
  geom_bar(stat="identity",
           width=0.5,
           fill= "white") +
  theme(axis.text.x = element_text(angle=90, vjust=0.6),
        legend.position="none") + 
  labs(title="Top10 Happiest Countries-2020",
       x="Country",y="Rank")
g2 <- ggplot(top10_2021,
             aes(x=factor(Country,levels=Country),
                 y=RANK, color = Country))+
  geom_bar(stat="identity",
           width=0.5,
           fill= "white") +  
  theme(axis.text.x = element_text(angle=90, vjust=0.6),
        legend.position="none") + 
  labs(title="Top10 Happiest Countries-2021",
       x="Country",y="Rank")

grid_arrange_shared_legend(g1, g2, ncol = 2,nrow= 1)
```